apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-proxy-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: http://{{ .Release.Name }}-auth-service.{{ .Release.Namespace }}.svc.cluster.local/
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-auth-service
            port: 
              number: {{ .Values.authMicroservice.service.port }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-noauth
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /((user\/register)|(auth\/login)|(auth\/refresh))
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-auth-service
            port: 
              number: {{ .Values.authMicroservice.service.port }}