apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-service
spec:
  type: {{ .Values.authMicroservice.service.type }}
  selector:
    app: {{ .Release.Name }}-auth-app
  ports:
    - protocol: TCP
      port: {{ .Values.authMicroservice.service.port }}
      targetPort: {{ .Values.authMicroservice.port }}