{{- if (.Values.development).enabled -}}
#  теперь твои локальные приложения могут подключиться к сервисам внутри minikube
#  не забудь использовать forward port  для проксирования порта https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/
# kubectl port-forward homework-7-billing-mysql-0 3306:3306 & kubectl port-forward homework-7-billing-rabbitmq-0 5672:5672 & kubectl port-forward homework-7-billing-rabbitmq-0 15672:15672 & kubectl port-forward homework-7-billing-rabbitmq-0 4369:4369
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-development-service
spec:
  type: ExternalName
  externalName: host.minikube.internal
{{- end -}}