apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    {{- with (first .Values.microservices) }}
    nginx.ingress.kubernetes.io/auth-proxy-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: http://{{ $.Release.Name }}-{{ .app.name }}-service.{{ $.Release.Namespace }}.svc.cluster.local/
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      {{- range $app := .Values.microservices }}
      {{- range .app.paths }}
      - path: {{ . }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Release.Name }}-{{ $app.app.name }}-service
            port: 
              number: {{ $app.service.port }}
      {{- end }}
      {{- end }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-noauth
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      {{- with (first .Values.microservices) }}
      - path: /((user\/register)|(auth\/login)|(auth\/refresh))
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Release.Name }}-{{ .app.name }}-service
            port: 
              number: {{ .service.port }}
      {{- end }}