{{- range .Values.microservices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .app.name }}-service
spec:
  type: {{ .service.type }}
  selector:
    app: {{ $.Release.Name }}-{{ .app.name }}
  ports:
    - protocol: TCP
      port: {{ .service.port }}
      targetPort: {{ .app.port }}

---
{{- end }}