apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '80'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "*"
    
    ingress.kubernetes.io/cache-enable: "false"

    {{- with (first .Values.microservices) }}
    nginx.ingress.kubernetes.io/auth-proxy-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: http://{{ $.Release.Name }}-{{ .app.name }}-service.{{ $.Release.Namespace }}.svc.cluster.local/
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      {{- range $app := .Values.microservices }}
      {{- range .app.paths }}
      - path: {{ . }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Release.Name }}-{{ $app.app.name }}-service
            port: 
              number: {{ $app.service.port }}
      {{- end }}
      {{- end }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-noauth
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '80'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "*"
    
    ingress.kubernetes.io/cache-enable: "false"

    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      {{- range $app := .Values.microservices }}
      {{- if .app.publicPaths }}
      {{- range .app.publicPaths }}
      - path: {{ . }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Release.Name }}-{{ $app.app.name }}-service
            port: 
              number: {{ $app.service.port }}
      {{- end }}
      {{- end }}
      {{- end }}