apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: homework-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homework-app
  template:
    metadata:
      labels:
        app: homework-app
    spec:
      containers:
      - name: homework-2
        image: proferio/homework-2:0.0.1
        ports:
        - containerPort: 8000