# use  --set development.enabled=true or:
# development:
#   enabled: true

mysql:
  auth:
    # тут я еще не разобрался: как устаноыить пароль на БД и в то же время пробросить его в деплоймент ??
    rootPassword: "htrhwrthwtjhwtjwtwthrth"
    database: "auth3"

rabbitmq:
  auth:
    password: "trhkrtkjyerfgvfrrtr"
    username: "user"
    tls:
      enable: false
      sslOptionsVerify: "verify_none"
      failIfNoPeerCert: false
  ldap:
    tls:
      skipVerify: true
      verify: "verify_none"
  # #START
  # extraSecrets:
  #   load-definition:
  #     load_definition.json: |
  #       {
  #         "users": [
  #           {
  #             "name": "{{ .Values.auth.username }}",
  #             "password": "{{ .Values.auth.password }}",
  #             "tags": "administrator"
  #           }
  #         ],
  #         "vhosts": [
  #           {
  #             "name": "/"
  #           }
  #         ]
  #       }
  # loadDefinition:
  #   enabled: true
  #   existingSecret: load-definition
  # extraConfiguration: |
  #   load_definitions = /app/load_definition.json
  # # END

replicaCount: 2

authMicroservice:
  app:
    repository: "proferio/homework-6"
    tag: "v0.0.1"
    port: 8000
  service:
    type: ClusterIP
    port: 80

prometheus:
  alertmanager:
    enabled: false

  pushgateway:
    enabled: false

  nodeExporter:
    enabled: false

grafana:
  persistence:
    enabled: true
  service:
    type: NodePort
