# use  --set development.enabled=true or:
# development:
#   enabled: true

mysql:
  auth:
    # тут я еще не разобрался: как устаноыить пароль на БД и в то же время пробросить его в деплоймент ??
    rootPassword: "htrhwrthwtjhwtjwtwthrth"
    database: "auth3"

rabbitmq:
  auth:
    password: "trhkrtkjyerfgvfrrtr"
    username: "user"
    tls:
      enable: false
      sslOptionsVerify: "verify_none"
      failIfNoPeerCert: false
  ldap:
    tls:
      skipVerify: true
      verify: "verify_none"

replicaCount: 2

authMicroservice:
  app:
    name: "auth-app"
    repository: "proferio/homework-7"
    tag: "v0.0.1"
    port: 8000
    amqp:
      queue: "order-service"
    paths:
      - "/"
      - "/user"
      - "/users"
      - "/auth"
  service:
    type: ClusterIP
    port: 80

microservices:
  - app:
      name: "auth-app"
      repository: "proferio/homework-7"
      tag: "v0.0.1"
      port: 8000
      amqp:
        queue: "auth-service"
      paths:
        - "/user"
        - "/users"
        - "/auth"
    service:
      type: ClusterIP
      port: 80
  - app:
      name: "billing-app"
      repository: "proferio/homework-7"
      tag: "v0.0.1"
      port: 8000
      amqp:
        queue: "billing-service"
      paths:
        - "/billing"
    service:
      type: ClusterIP
      port: 80
  - app:
      name: "notification-app"
      repository: "proferio/homework-7"
      tag: "v0.0.1"
      port: 8000
      amqp:
        queue: "notification-service"
      paths:
        - "/notification"
    service:
      type: ClusterIP
      port: 80
  - app:
      name: "order-app"
      repository: "proferio/homework-7"
      tag: "v0.0.1"
      port: 8000
      amqp:
        queue: "order-service"
      paths:
        - "/order"
    service:
      type: ClusterIP
      port: 80

prometheus:
  alertmanager:
    enabled: false

  pushgateway:
    enabled: false

  nodeExporter:
    enabled: false

grafana:
  persistence:
    enabled: true
  service:
    type: NodePort
